class Food {
  final String name;
  final String restaurant;
  final String price;
  final String rating;
  final String reviews;
  final String calories;
  final String time;
  final String image;
  final String description;
  final String category;

  Food({
    required this.name,
    required this.restaurant,
    required this.price,
    required this.rating,
    required this.reviews,
    required this.calories,
    required this.time,
    required this.image,
    required this.description,
    required this.category,
  });
}

final List<Food> bestSellers = [
  // PIZZA (6 items)
  Food(
    name: 'Melting Cheese Pizza',
    restaurant: 'Pizza Italiano',
    price: '10.99',
    rating: '4.8',
    reviews: '2.2k',
    calories: '450 Cal',
    time: '20 min',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=400',
    description: 'A delicious melting cheese pizza with fresh herbs and premium mozzarella.',
    category: 'Pizza',
  ),
  Food(
    name: 'Pepperoni Feast',
    restaurant: 'Slice Heaven',
    price: '12.99',
    rating: '4.9',
    reviews: '1.8k',
    calories: '520 Cal',
    time: '25 min',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&q=80&w=400',
    description: 'Loaded with double pepperoni and extra cheese on a crispy crust.',
    category: 'Pizza',
  ),
  Food(
    name: 'Veggie Supreme',
    restaurant: 'Green Slice',
    price: '11.50',
    rating: '4.7',
    reviews: '950',
    calories: '380 Cal',
    time: '22 min',
    image: 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&q=80&w=400',
    description: 'Bell peppers, onions, mushrooms, and olives on a thin crust.',
    category: 'Pizza',
  ),
  Food(
    name: 'BBQ Chicken Pizza',
    restaurant: 'Grill & Slice',
    price: '13.99',
    rating: '4.6',
    reviews: '1.1k',
    calories: '490 Cal',
    time: '25 min',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=400',
    description: 'Tangy BBQ sauce, grilled chicken, and red onions.',
    category: 'Pizza',
  ),
  Food(
    name: 'Margherita Classic',
    restaurant: 'Rome Kitchen',
    price: '9.99',
    rating: '4.8',
    reviews: '3.5k',
    calories: '340 Cal',
    time: '15 min',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=400',
    description: 'Simple and elegant with fresh basil, tomatoes, and buffalo mozzarella.',
    category: 'Pizza',
  ),
  Food(
    name: 'Hawaiian Party',
    restaurant: 'Aloha Pizza',
    price: '11.99',
    rating: '4.4',
    reviews: '800',
    calories: '410 Cal',
    time: '20 min',
    image: 'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&q=80&w=400',
    description: 'The classic mix of ham and sweet pineapple.',
    category: 'Pizza',
  ),

  // BURGERS (6 items)
  Food(
    name: 'Cheese burger',
    restaurant: 'Burger Hunt',
    price: '4.99',
    rating: '4.5',
    reviews: '1.5k',
    calories: '600 Cal',
    time: '15 min',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=400',
    description: 'Gourmet cheese burger with fresh lettuce, tomato, and our secret sauce.',
    category: 'Burgers',
  ),
  Food(
    name: 'Double Beef King',
    restaurant: 'Mega Burger',
    price: '8.99',
    rating: '4.8',
    reviews: '2.1k',
    calories: '850 Cal',
    time: '18 min',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=400',
    description: 'Two juicy beef patties with cheddar cheese and pickles.',
    category: 'Burgers',
  ),
  Food(
    name: 'Spicy Zinger',
    restaurant: 'Chicken Run',
    price: '5.50',
    rating: '4.6',
    reviews: '1.3k',
    calories: '550 Cal',
    time: '12 min',
    image: 'https://images.unsplash.com/photo-1525351326368-efbb5cb6814d?auto=format&fit=crop&q=80&w=400',
    description: 'Crispy spicy chicken fillet with jalapeños and mayo.',
    category: 'Burgers',
  ),
  Food(
    name: 'Bacon Deluxe',
    restaurant: 'Smoke House',
    price: '7.99',
    rating: '4.7',
    reviews: '900',
    calories: '720 Cal',
    time: '20 min',
    image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&q=80&w=400',
    description: 'Smoky bacon, caramelized onions, and swiss cheese.',
    category: 'Burgers',
  ),
  Food(
    name: 'Veggie Garden',
    restaurant: 'Pure Eats',
    price: '6.50',
    rating: '4.3',
    reviews: '600',
    calories: '420 Cal',
    time: '15 min',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=400',
    description: 'Plant-based patty with avocado and sprouts.',
    category: 'Burgers',
  ),
  Food(
    name: 'Mushroom Swiss',
    restaurant: 'Steak & Shake',
    price: '7.50',
    rating: '4.5',
    reviews: '1.1k',
    calories: '680 Cal',
    time: '18 min',
    image: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?auto=format&fit=crop&q=80&w=400',
    description: 'Sauteed mushrooms and melted swiss cheese.',
    category: 'Burgers',
  ),

  // SUSHI (6 items)
  Food(
    name: 'Salmon Nigiri',
    restaurant: 'Sushi Zen',
    price: '14.99',
    rating: '4.9',
    reviews: '1.2k',
    calories: '200 Cal',
    time: '15 min',
    image: 'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&q=80&w=400',
    description: 'Fresh Atlantic salmon over seasoned sushi rice.',
    category: 'Sushi',
  ),
  Food(
    name: 'California Roll',
    restaurant: 'Tokyo Express',
    price: '9.99',
    rating: '4.6',
    reviews: '2.5k',
    calories: '300 Cal',
    time: '12 min',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&q=80&w=400',
    description: 'Crab meat, avocado, and cucumber with sesame seeds.',
    category: 'Sushi',
  ),
  Food(
    name: 'Dragon Roll',
    restaurant: 'Dragon Sushi',
    price: '16.50',
    rating: '4.8',
    reviews: '850',
    calories: '450 Cal',
    time: '20 min',
    image: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&q=80&w=400',
    description: 'Shrimp tempura and cucumber topped with eel and avocado.',
    category: 'Sushi',
  ),
  Food(
    name: 'Spicy Tuna Roll',
    restaurant: 'Omi Sushi',
    price: '11.99',
    rating: '4.7',
    reviews: '1.5k',
    calories: '280 Cal',
    time: '15 min',
    image: 'https://images.unsplash.com/photo-1559466273-d95e72debaf8?auto=format&fit=crop&q=80&w=400',
    description: 'Diced tuna with spicy mayo and green onions.',
    category: 'Sushi',
  ),
  Food(
    name: 'Veggie Maki',
    restaurant: 'Green Sushi',
    price: '7.99',
    rating: '4.4',
    reviews: '400',
    calories: '180 Cal',
    time: '10 min',
    image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?auto=format&fit=crop&q=80&w=400',
    description: 'Pickled radish, cucumber, and carrot.',
    category: 'Sushi',
  ),
  Food(
    name: 'Sashimi Platter',
    restaurant: 'Ocean Fresh',
    price: '22.00',
    rating: '4.9',
    reviews: '600',
    calories: '350 Cal',
    time: '25 min',
    image: 'https://images.unsplash.com/photo-1583623025817-d180a2221d0a?auto=format&fit=crop&q=80&w=400',
    description: 'Chef\'s selection of the day\'s freshest raw fish.',
    category: 'Sushi',
  ),

  // SALADS (6 items)
  Food(
    name: 'Chicken Salad',
    restaurant: 'Melt House',
    price: '4.56',
    rating: '4.2',
    reviews: '800',
    calories: '220 Cal',
    time: '15 min',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=400',
    description: 'Fresh chicken salad with mixed greens and grilled chicken.',
    category: 'Salads',
  ),
  Food(
    name: 'Greek Goddess',
    restaurant: 'Olive Grove',
    price: '8.99',
    rating: '4.7',
    reviews: '1.1k',
    calories: '310 Cal',
    time: '12 min',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&q=80&w=400',
    description: 'Feta cheese, olives, cucumbers, and balsamic glaze.',
    category: 'Salads',
  ),
  Food(
    name: 'Caesar Salad',
    restaurant: 'Empire Salads',
    price: '9.50',
    rating: '4.6',
    reviews: '2.3k',
    calories: '450 Cal',
    time: '15 min',
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&q=80&w=400',
    description: 'Romaine lettuce, croutons, and parmesan with Caesar dressing.',
    category: 'Salads',
  ),
  Food(
    name: 'Quinoa Bowl',
    restaurant: 'Healthy Hub',
    price: '10.99',
    rating: '4.5',
    reviews: '750',
    calories: '380 Cal',
    time: '18 min',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=400',
    description: 'Organic quinoa with roasted sweet potatoes and kale.',
    category: 'Salads',
  ),
  Food(
    name: 'Fruit Salad',
    restaurant: 'Berry Sweet',
    price: '6.99',
    rating: '4.8',
    reviews: '500',
    calories: '150 Cal',
    time: '10 min',
    image: 'https://images.unsplash.com/photo-1519996529931-28324d5a630e?auto=format&fit=crop&q=80&w=400',
    description: 'Seasonal fresh fruit mix with a honey-lime dressing.',
    category: 'Salads',
  ),
  Food(
    name: 'Cobb Salad',
    restaurant: 'Classic Eats',
    price: '11.50',
    rating: '4.7',
    reviews: '900',
    calories: '550 Cal',
    time: '20 min',
    image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&q=80&w=400',
    description: 'Chicken, avocado, egg, bacon, and blue cheese.',
    category: 'Salads',
  ),

  // DRINKS (6 items)
  Food(
    name: 'Orange Juice',
    restaurant: 'Fresh Squeeze',
    price: '3.99',
    rating: '4.9',
    reviews: '2.1k',
    calories: '120 Cal',
    time: '5 min',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&q=80&w=400',
    description: '100% freshly squeezed California oranges.',
    category: 'Drinks',
  ),
  Food(
    name: 'Iced Latte',
    restaurant: 'Bean Brew',
    price: '4.50',
    rating: '4.8',
    reviews: '1.5k',
    calories: '180 Cal',
    time: '8 min',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&q=80&w=400',
    description: 'Cold espresso with creamy milk and a hint of vanilla.',
    category: 'Drinks',
  ),
  Food(
    name: 'Mango Smoothie',
    restaurant: 'Tropical Bar',
    price: '5.99',
    rating: '4.7',
    reviews: '800',
    calories: '250 Cal',
    time: '10 min',
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&q=80&w=400',
    description: 'Real mango blended with yogurt and ice.',
    category: 'Drinks',
  ),
  Food(
    name: 'Coca Cola',
    restaurant: 'Soda Shop',
    price: '2.50',
    rating: '4.5',
    reviews: '5k',
    calories: '140 Cal',
    time: '2 min',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=400',
    description: 'The classic refreshing cola.',
    category: 'Drinks',
  ),
  Food(
    name: 'Green Tea',
    restaurant: 'Zen Drinks',
    price: '3.50',
    rating: '4.8',
    reviews: '900',
    calories: '0 Cal',
    time: '5 min',
    image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?auto=format&fit=crop&q=80&w=400',
    description: 'Hot organic green tea with a lemon wedge.',
    category: 'Drinks',
  ),
  Food(
    name: 'Strawberry Milkshake',
    restaurant: 'Creamy Corner',
    price: '6.50',
    rating: '4.6',
    reviews: '1.2k',
    calories: '480 Cal',
    time: '12 min',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&q=80&w=400',
    description: 'Thick and creamy strawberry milkshake with whipped cream.',
    category: 'Drinks',
  ),
];
